# Generated by Django 3.0.6 on 2020-05-15 14:08
from django.conf import settings
from django.db import migrations, transaction


def forwards_func(apps, schema_editor):
    if settings.DEBUG:
        # Only in DEBUG mode!
        try:
            from authapp.models import ShopUser

            with transaction.atomic():
                ShopUser.objects.create_superuser(
                    "admin", "root@google.com", "admin", age=33)
        except:
            print("Cann't create super user for debug")


def reverse_func(apps, schema_editor):
    if settings.DEBUG:
        # Only in DEBUG mode!
        try:
            from authapp.models import ShopUserpy

            with transaction.atomic():
                ShopUser.objects.all().delete()
        except:
            print("Cann't delete super user for debug")


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)
    ]
