# Generated by Django 2.2.3 on 2020-06-10 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 18, 45, 2, 785007, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
