# Generated by Django 2.2.3 on 2020-06-15 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20200614_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 7, 6, 29, 562951, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
