# Generated by Django 2.2.3 on 2020-06-15 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20200615_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 8, 0, 52, 602788, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
