# Generated by Django 2.2.3 on 2020-06-17 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20200615_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 13, 4, 12, 493004, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
