# Generated by Django 2.2.3 on 2020-06-25 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20200617_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 10, 52, 56, 892924, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
